import type { CollectionConfig } from 'payload'

/**
 * Exercises — one row per Quiz question in the source markdown.
 *
 * `payload` JSON field stores type-specific data with id-keyed choices for
 * safe reordering:
 *
 *   multiple-choice:
 *     { choices: [{id:'a', text:'Saint-Émilion'}, {id:'b', text:'Pauillac'}, ...],
 *       correctIds: ['b'] }
 *
 *   multiple-select:
 *     { choices: [{id:'a', text:'...'}, ...],
 *       correctIds: ['a', 'c'] }
 *
 *   type-answer:
 *     { acceptedAnswers: ['Pinot Noir', 'pinot'], caseSensitive: false }
 */
export const Exercises: CollectionConfig = {
  slug: 'exercises',
  admin: {
    useAsTitle: 'prompt',
    defaultColumns: ['prompt', 'type', 'lesson', 'difficulty', 'isPublished'],
  },
  // versions: { drafts: true } — disabled for v1, see Lessons.ts note.
  access: {
    read: () => true,
    create: ({ req: { user } }) => !!user,
    update: ({ req: { user } }) => !!user,
    delete: ({ req: { user } }) => !!user,
  },
  fields: [
    { name: 'slug', type: 'text', admin: { description: 'Auto-generated from prompt' } },
    {
      name: 'type',
      type: 'select',
      required: true,
      options: [
        { label: 'Multiple Choice', value: 'multiple-choice' },
        { label: 'Multiple Select', value: 'multiple-select' },
        { label: 'Type the Answer', value: 'type-answer' },
      ],
    },
    { name: 'prompt', type: 'text', required: true },
    {
      name: 'payload',
      type: 'json',
      required: true,
      admin: { description: 'Type-specific shape with id-keyed choices. See header comment.' },
    },
    {
      name: 'explanation',
      type: 'richText',
      admin: { description: 'Shown after answer attempt' },
    },
    {
      name: 'lesson',
      type: 'relationship',
      relationTo: 'lessons',
      admin: { description: 'Required for module quiz exercises. Leave blank for exam-only exercises (linked via exam.questionPool).' },
    },
    {
      name: 'difficulty',
      type: 'select',
      defaultValue: 'medium',
      options: [
        { label: 'Easy', value: 'easy' },
        { label: 'Medium', value: 'medium' },
        { label: 'Hard', value: 'hard' },
      ],
    },
    {
      name: 'topicTags',
      type: 'array',
      admin: { description: 'Inherited from lesson at import time; can be refined' },
      fields: [{ name: 'tag', type: 'text', required: true }],
    },
    {
      name: 'source',
      type: 'select',
      defaultValue: 'imported',
      options: [
        { label: 'Imported from markdown', value: 'imported' },
        { label: 'Hand-authored', value: 'authored' },
        { label: 'Generated by RAG', value: 'generated' },
      ],
    },
    {
      name: 'examOnly',
      type: 'checkbox',
      defaultValue: false,
      admin: {
        description: 'If true, not surfaced in Daily Session — only available in exam mode',
      },
    },
    { name: 'isPublished', type: 'checkbox', defaultValue: false },
    { name: 'reviewedBy', type: 'relationship', relationTo: 'users' },
    { name: 'reviewedAt', type: 'date' },
  ],
}
